GET http://127.0.0.1:8000/api/secret/834y5w
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/secret
Content-Type: application/json

{
    "secretText": "Test posting secret test",
    "expireAfterViews": 3,
    "expireAfter": 10
}